version: "3"
services:
  database:
    image: postgres:10-alpine
    environment:
      - POSTGERS_PASSWORD=postgres
    volumes:
      - docker-example-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: .
    image: consul-app
    command: bundle exec rails s -p 3000 -b "0.0.0.0"
    working_dir: /var/www/consul
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - NEW_RELIC_AGENT_ENABLED=false
      - DATABASE_HOST=database
      - DATABASE_NAME=consul_production
      - SMTP_DOMAIN=codefor.nl
      - SMTP_HOST=smtp.mailgun.org
      - SMTP_PASSWORD=a6d631757784f24beace64715c850781
      - SMTP_USER=postmaster@codefor.nl
      - SMTP_FROM=no-reply@codefor.nl
    depends_on:
      - database
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www/consul:delegated
      - bundle:/usr/local/bundle:delegated

  custom:
    image: consul-app
    environment:
      - DATABASE_HOST=database
      - DATABASE_NAME=postgres
      - CUSTOM_SET_NAME=rommeldam
    command: ./scripts/customize.sh
    volumes:
      - .:/var/www/consul:delegated
      - bundle:/usr/local/bundle:delegated
    depends_on:
      - app
      - database

volumes:
  docker-example-postgres: {}
  bundle: {}

